import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/navbar/Navbar";
import Model from "./Components/model/Model";
import LoginModel from "./Components/model/LoginModel";
import SignUpModel from "./Components/model/SignUpModel";
import AddPropertyModal from "./Components/model/AddPropertyModal";
import SearchModal from "./Components/model/SearchModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Airbnb",
  description: "Generated by create next app",
};

const content=(
  
    <p>Lorem ipsum dolor sit amet consectetur.</p>
  
)
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <div className="pt-24">{children}</div>
        {/* <Model
        label="Modal test"
        content={content}
        isOpen={false}
        /> */}
        <LoginModel/>
        <SearchModal/>
        <SignUpModel/>
        <AddPropertyModal/>
      </body>
    </html>
  );
}
